// src/lib/components/About.svelte
<script>
  const since = 2018
  const elapsedYear = new Date().getFullYear() - since
</script>

<div id="about">
  <h1 class="text-lg block font-bold text-primary mt-3">About</h1>
  <p class="text-gray-300">
    I'm a software developer with almost {elapsedYear} years of experience developing web
    applications. I mostly use Laravel, Tailwind, and Vue, I can also use
    other tools like Node.js, Go, Typescript, and Svelte.
  </p>
</div>

// src/components/About.vue
<template>
  <div id="about">
    <h1 class="text-lg block font-bold text-white mt-3">About</h1>
    <p class="text-gray-300">
      I'm a software developer with almost 5 years of experience developing web
      applications. I mostly use Laravel, Tailwind, and Vue, I can also use
      other tools like Node.js, Go, Typescript, and Svelte.
    </p>
  </div>
</template>
