// src/components/Experience.svelte
<div id="experience">
  <h1 class="text-lg block font-bold text-white mt-3 mb-1">Experience</h1>
  <div class="flex flex-col gap-4 sm:pl-4">
    <div>
      <div class="text-white flex flex-col sm:flex-row justify-between">
        <h2 class="font-medium">Hiraya MNL - Full Stack Developer</h2>
        <span class="text-xs"> August 2020 - Feb 2023 </span>
      </div>
      <ul class="list-disc text-gray-300 pl-6 sm:pl-8 mt-2 text-sm">
        <li>Develop notification system and other modules for CLMS</li>
        <li>Help with the development of Paydro dashboard</li>
        <li>Develop an API that scrape for certain keywords</li>
        <li>
          Develop an API for both web and mobile that finds nearest lay-bare
          branch
        </li>
        <li>Handle server deployment of clms and laybare projects</li>
      </ul>
    </div>

    <div>
      <div class="text-white flex flex-col sm:flex-row justify-between">
        <h2 class="font-medium">OrangeApps Inc. - Software Developer</h2>
        <span class="text-xs"> July 2018 - July 2020 </span>
      </div>
      <ul class="list-disc text-gray-300 pl-6 sm:pl-8 mt-2 text-sm">
        <li>Develop notification system and other modules for CLMS</li>
        <li>Help with the development of Paydro dashboard</li>
        <li>Develop an API that scrape for certain keywords</li>
        <li>
          Develop an API for both web and mobile that finds nearest lay-bare
          branch
        </li>
        <li>Handle server deployment of clms and laybare projects</li>
      </ul>
    </div>

    <div>
      <div class="text-white flex flex-col sm:flex-row justify-between">
        <h2 class="font-medium">Software Quality Assurance (Internship)</h2>
        <span class="text-xs"> March 2018 - April 2020 </span>
      </div>
      <ul class="list-disc text-gray-300 pl-6 sm:pl-8 mt-2 text-sm">
        <li>Test the platform features and functionality</li>
        <li>Report bugs and UI problems found</li>
      </ul>
    </div>
  </div>
</div>

// src/components/Experience.vue
<template>
  <div id="experience">
    <h1 class="text-lg block font-bold text-white mt-3 mb-1">Experience</h1>
    <div class="flex flex-col gap-4 sm:pl-4">
      <div>
        <div class="text-white flex flex-col sm:flex-row justify-between">
          <h2 class="font-medium">Hiraya MNL - Full Stack Developer</h2>
          <span class="text-xs"> August 2020 - Feb 2023 </span>
        </div>
        <ul class="list-disc text-gray-300 pl-6 sm:pl-8 mt-2 text-sm">
          <li>Develop notification system and other modules for CLMS</li>
          <li>Help with the development of Paydro dashboard</li>
          <li>Develop an API that scrape for certain keywords</li>
          <li>
            Develop an API for both web and mobile that finds nearest lay-bare
            branch
          </li>
          <li>Handle server deployment of clms and laybare projects</li>
        </ul>
      </div>

      <div>
        <div class="text-white flex flex-col sm:flex-row justify-between">
          <h2 class="font-medium">OrangeApps Inc. - Software Developer</h2>
          <span class="text-xs"> July 2018 - July 2020 </span>
        </div>
        <ul class="list-disc text-gray-300 pl-6 sm:pl-8 mt-2 text-sm">
          <li>Develop notification system and other modules for CLMS</li>
          <li>Help with the development of Paydro dashboard</li>
          <li>Develop an API that scrape for certain keywords</li>
          <li>
            Develop an API for both web and mobile that finds nearest lay-bare
            branch
          </li>
          <li>Handle server deployment of clms and laybare projects</li>
        </ul>
      </div>

      <div>
        <div class="text-white flex flex-col sm:flex-row justify-between">
          <h2 class="font-medium">Software Quality Assurance (Internship)</h2>
          <span class="text-xs"> March 2018 - April 2020 </span>
        </div>
        <ul class="list-disc text-gray-300 pl-6 sm:pl-8 mt-2 text-sm">
          <li>Test the platform features and functionality</li>
          <li>Report bugs and UI problems found</li>
        </ul>
      </div>
    </div>
  </div>
</template>
<script setup></script>
