// src/components/Links.vue
<template>
    <div id="links">
        <h1 class="block text-lg font-bold text-white mt-3 mb-1">Links</h1>
        <div class="flex flex-col text-white">
            <div>
                LinkedIn:
                <a href="https://www.linkedin.com/in/jezerdave/" target="_blank" class="underline">@jezerdave</a>
            </div>
            <div>
                Github:
                <a href="https://github.com/sush1lemon/" target="_blank" class="underline">@sush1lemon</a>
            </div>
            <div>
                Stackoverflow:
                <a href="https://stackoverflow.com/users/21624652/swooshi" target="_blank"
                   class="underline">@swooshi</a>
            </div>
            <div>
                Discord:
                <a href="https://discord.com/" target="_blank" class="underline">@sush1lemon#4863</a>
            </div>
        </div>
    </div>
</template>
<script>
export default {
    name: 'Links'
}
</script>

// src/lib/components/Links.svelte
<div id="links">
    <h1 class="block text-lg font-bold text-pretty mt-3 mb-1">Socials</h1>
    <div class="flex flex-col text-pretty">
        <div>
            LinkedIn:
            <a href="https://www.linkedin.com/in/jezerdave/" target="_blank" class="underline">@jezerdave</a>
        </div>
        <div>
            Github:
            <a href="https://github.com/sush1lemon/" target="_blank" class="underline">@sush1lemon</a>
        </div>
        <div>
            Stackoverflow:
            <a href="https://stackoverflow.com/users/21624652/swooshi" target="_blank"
               class="underline">@swooshi</a>
        </div>
        <div>
            Discord:
            <a href="https://discord.com/" target="_blank" class="underline">@swooshii.</a>
        </div>
    </div>
</div>
